language: objective-c
os:
  - osx
before_install:
  - sw_vers
  - brew update
  - brew install ansible
  - mkdir roles
  - ansible-galaxy install -r requirements.yml -p ./roles
script:
  - ansible-playbook -vv playbook.yml -i hosts
notifications:
    slack: shimi-rsslack:bUoxLktUdcotH8rYgMyCcTJR
