language: objective-c
os:
  - osx
before_install:
  - sw_vers
  - brew update
  - brew install ansible
  - ansible-playbook -vv playbook.yml -i hosts
# script:
#   - make test
notifications:
    slack: shimi-rsslack:bUoxLktUdcotH8rYgMyCcTJR
