language: objective-c
os:
  - osx
before_install:
  - sw_vers
  - brew update
  - brew install ansible
  - ansible --version
script:
  - ansible-playbook -vv playbook.yml -i hosts
notifications:
    slack: shimi-rsslack:bUoxLktUdcotH8rYgMyCcTJR
